use crate::*;

#[derive(Clone, Debug, PartialEq)]
pub(crate) enum IpeMoneyCurrency {
    USD,
    EUR,
    GBP,
    JPY,
    CHF,
    AUD,
    CAD,
    NZD,
    SEK,
    NOK,
    DKK,
    CNY,
    HKD,
    SGD,
    KRW,
    TWD,
    INR,
    THB,
    MYR,
    IDR,
    PHP,
    VND,
    BRL,
    MXN,
    ARS,
    CLP,
    ZAR,
    TRY,
    RUB,
    UAH,
    PLN,
    CZK,
    HUF,
    RON,
    BGN,
    AED,
    SAR,
    QAR,
    KWD,
    BHD,
    OMR,
    JOD,
    ILS,
    EGP,
    NGN,
    KES,
    GHS,
    MAD,
    TND,
    DZD,
    PKR,
    BDT,
    LKR,
    NPR,
    BTC,
    ETH,
    USDT,
    USDC,
    CurrencyRaw(String),
}
impl IpeStringify for IpeMoneyCurrency {
    fn ipe_show(&self) -> String {
        match self {
            IpeMoneyCurrency::USD => "USD".to_string(),
            IpeMoneyCurrency::EUR => "EUR".to_string(),
            IpeMoneyCurrency::GBP => "GBP".to_string(),
            IpeMoneyCurrency::JPY => "JPY".to_string(),
            IpeMoneyCurrency::CHF => "CHF".to_string(),
            IpeMoneyCurrency::AUD => "AUD".to_string(),
            IpeMoneyCurrency::CAD => "CAD".to_string(),
            IpeMoneyCurrency::NZD => "NZD".to_string(),
            IpeMoneyCurrency::SEK => "SEK".to_string(),
            IpeMoneyCurrency::NOK => "NOK".to_string(),
            IpeMoneyCurrency::DKK => "DKK".to_string(),
            IpeMoneyCurrency::CNY => "CNY".to_string(),
            IpeMoneyCurrency::HKD => "HKD".to_string(),
            IpeMoneyCurrency::SGD => "SGD".to_string(),
            IpeMoneyCurrency::KRW => "KRW".to_string(),
            IpeMoneyCurrency::TWD => "TWD".to_string(),
            IpeMoneyCurrency::INR => "INR".to_string(),
            IpeMoneyCurrency::THB => "THB".to_string(),
            IpeMoneyCurrency::MYR => "MYR".to_string(),
            IpeMoneyCurrency::IDR => "IDR".to_string(),
            IpeMoneyCurrency::PHP => "PHP".to_string(),
            IpeMoneyCurrency::VND => "VND".to_string(),
            IpeMoneyCurrency::BRL => "BRL".to_string(),
            IpeMoneyCurrency::MXN => "MXN".to_string(),
            IpeMoneyCurrency::ARS => "ARS".to_string(),
            IpeMoneyCurrency::CLP => "CLP".to_string(),
            IpeMoneyCurrency::ZAR => "ZAR".to_string(),
            IpeMoneyCurrency::TRY => "TRY".to_string(),
            IpeMoneyCurrency::RUB => "RUB".to_string(),
            IpeMoneyCurrency::UAH => "UAH".to_string(),
            IpeMoneyCurrency::PLN => "PLN".to_string(),
            IpeMoneyCurrency::CZK => "CZK".to_string(),
            IpeMoneyCurrency::HUF => "HUF".to_string(),
            IpeMoneyCurrency::RON => "RON".to_string(),
            IpeMoneyCurrency::BGN => "BGN".to_string(),
            IpeMoneyCurrency::AED => "AED".to_string(),
            IpeMoneyCurrency::SAR => "SAR".to_string(),
            IpeMoneyCurrency::QAR => "QAR".to_string(),
            IpeMoneyCurrency::KWD => "KWD".to_string(),
            IpeMoneyCurrency::BHD => "BHD".to_string(),
            IpeMoneyCurrency::OMR => "OMR".to_string(),
            IpeMoneyCurrency::JOD => "JOD".to_string(),
            IpeMoneyCurrency::ILS => "ILS".to_string(),
            IpeMoneyCurrency::EGP => "EGP".to_string(),
            IpeMoneyCurrency::NGN => "NGN".to_string(),
            IpeMoneyCurrency::KES => "KES".to_string(),
            IpeMoneyCurrency::GHS => "GHS".to_string(),
            IpeMoneyCurrency::MAD => "MAD".to_string(),
            IpeMoneyCurrency::TND => "TND".to_string(),
            IpeMoneyCurrency::DZD => "DZD".to_string(),
            IpeMoneyCurrency::PKR => "PKR".to_string(),
            IpeMoneyCurrency::BDT => "BDT".to_string(),
            IpeMoneyCurrency::LKR => "LKR".to_string(),
            IpeMoneyCurrency::NPR => "NPR".to_string(),
            IpeMoneyCurrency::BTC => "BTC".to_string(),
            IpeMoneyCurrency::ETH => "ETH".to_string(),
            IpeMoneyCurrency::USDT => "USDT".to_string(),
            IpeMoneyCurrency::USDC => "USDC".to_string(),
            IpeMoneyCurrency::CurrencyRaw(p0) => format!(
                "CurrencyRaw {}",
                (&ipe_runtime::stringify::Wrap(p0)).dispatch()
            ),
        }
    }
}
#[derive(Clone, Debug, PartialEq)]
pub(crate) enum IpeMoneyMoney {
    Money(ipe_runtime::decimal::Decimal, IpeMoneyCurrency),
}
impl IpeStringify for IpeMoneyMoney {
    fn ipe_show(&self) -> String {
        match self {
            IpeMoneyMoney::Money(p0, p1) => format!(
                "Money {} {}",
                (&ipe_runtime::stringify::Wrap(p0)).dispatch(),
                (&ipe_runtime::stringify::Wrap(p1)).dispatch()
            ),
        }
    }
}
