name = "skymon"
version = "0.1.0"
entry = "src/Main.sky"

[source]
root = "src"

[live]
port = 8000
store = "sqlite"
storePath = "skymon.db"

[database]
driver = "sqlite"
path = "skymon.db"

["go.dependencies"]
"crypto/sha256" = "latest"
"encoding/hex" = "latest"
