[package]
name = "sky_db"
edition.workspace = true
version.workspace = true

[dependencies]
salsa = "=0.27.2"
sky_intern = { path = "../sky_intern" }
sky_diagnostics = { path = "../sky_diagnostics" }
sky_syntax = { path = "../sky_syntax" }
sky_parse = { path = "../sky_parse" }
sky_canon = { path = "../sky_canon" }
sky_types = { path = "../sky_types" }
sky_kernels = { path = "../sky_kernels" }
sky_lower = { path = "../sky_lower" }
sky_ir = { path = "../sky_ir" }

[lints]
workspace = true
