//! The `ipe.lock` lockfile: exact resolved dependencies, pinned for a
//! reproducible build.
//!
//! Each locked dependency records the resolved version, the source repository,
//! its exact revision, and the sha256 of the fetched source tree. A build reads
//! these pins rather than re-resolving through the index, so it is reproducible
//! even when the index is unreachable, and the pinned hash lets a later build
//! re-verify the source it fetches.
//!
//! Serialization is deterministic: packages are always written sorted by name,
//! so two runs that resolve the same set produce byte-identical lockfiles (a
//! stable diff, no spurious churn).

use std::path::{Path, PathBuf};

use crate::CliError;

/// The lockfile's filename at a project root.
const LOCKFILE_NAME: &str = "ipe.lock";

/// One locked dependency: the exact resolved version and the integrity anchors
/// (`source` + `rev` + `sha256`) a reproducible, re-verifiable build needs.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LockedDep {
    /// The package name (the lockfile's sort key).
    pub name: String,
    /// The exact resolved version.
    pub version: semver::Version,
    /// The source repository the package was fetched from.
    pub source: String,
    /// The exact revision fetched.
    pub rev: String,
    /// The sha256 of the fetched source tree, verified on fetch and re-verifiable
    /// on a later build.
    pub sha256: String,
}

/// The parsed `ipe.lock`: the set of locked dependencies, held sorted by name so
/// every write is deterministic.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Lockfile {
    packages: Vec<LockedDep>,
}

impl Lockfile {
    /// Read the lockfile at `project_root/ipe.lock`. A missing lockfile is an
    /// empty lockfile (a project with no locked dependencies yet), not an error.
    ///
    /// # Errors
    /// [`CliError::Io`] if the file exists but cannot be read; [`CliError::Resolve`]
    /// if its content is malformed (a bad version, a missing field).
    pub fn read(project_root: &Path) -> Result<Self, CliError> {
        let path = Self::path(project_root);
        let text = match std::fs::read_to_string(&path) {
            Ok(text) => text,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Self::default()),
            Err(e) => return Err(CliError::Io { path, source: e }),
        };
        parse(&text)
    }

    /// Write the lockfile to `project_root/ipe.lock`, packages sorted by name.
    ///
    /// # Errors
    /// [`CliError::Io`] if the file cannot be written.
    pub fn write(&self, project_root: &Path) -> Result<(), CliError> {
        let path = Self::path(project_root);
        std::fs::write(&path, self.render()).map_err(|e| CliError::Io { path, source: e })
    }

    /// Insert `dep`, replacing any existing entry with the same name. The set
    /// stays sorted by name.
    pub fn upsert(&mut self, dep: LockedDep) {
        match self.packages.binary_search_by(|p| p.name.cmp(&dep.name)) {
            Ok(at) => {
                if let Some(slot) = self.packages.get_mut(at) {
                    *slot = dep;
                }
            }
            Err(at) => self.packages.insert(at, dep),
        }
    }

    /// Remove the entry named `name`, returning whether one was present.
    pub fn remove(&mut self, name: &str) -> bool {
        match self
            .packages
            .binary_search_by(|p| p.name.as_str().cmp(name))
        {
            Ok(at) => {
                self.packages.remove(at);
                true
            }
            Err(_) => false,
        }
    }

    /// The locked dependencies, sorted by name.
    #[must_use]
    pub fn packages(&self) -> &[LockedDep] {
        &self.packages
    }

    /// The lockfile path for a project root.
    fn path(project_root: &Path) -> PathBuf {
        project_root.join(LOCKFILE_NAME)
    }

    /// Render the lockfile as deterministic TOML: a `[[package]]` table per
    /// dependency, in name order.
    fn render(&self) -> String {
        use std::fmt::Write as _;
        // Rendered from an already-sorted invariant; sort defensively so a
        // hand-constructed `Lockfile` still writes deterministically.
        let mut packages = self.packages.clone();
        packages.sort_by(|a, b| a.name.cmp(&b.name));
        let mut out = String::from(
            "# ipe.lock — resolved dependencies, pinned for a reproducible build.\n\
             # Generated by `ipe add`; do not edit by hand.\n",
        );
        for dep in &packages {
            let _ = write!(
                out,
                "\n[[package]]\nname = \"{}\"\nversion = \"{}\"\nsource = \"{}\"\n\
                 rev = \"{}\"\nsha256 = \"{}\"\n",
                dep.name, dep.version, dep.source, dep.rev, dep.sha256
            );
        }
        out
    }
}

/// Parse `ipe.lock` text into a [`Lockfile`], sorting packages by name so the
/// in-memory invariant holds regardless of file order.
fn parse(text: &str) -> Result<Lockfile, CliError> {
    let mut packages: Vec<LockedDep> = Vec::new();
    let mut current: Option<RawLocked> = None;

    for line in text.lines().map(str::trim) {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line == "[[package]]" {
            if let Some(raw) = current.take() {
                packages.push(raw.into_dep()?);
            }
            current = Some(RawLocked::default());
            continue;
        }
        if line.starts_with('[') {
            if let Some(raw) = current.take() {
                packages.push(raw.into_dep()?);
            }
            continue;
        }
        let Some((key, raw_val)) = line.split_once('=') else {
            continue;
        };
        let Some(record) = current.as_mut() else {
            continue;
        };
        let value = unquote(raw_val.trim()).to_owned();
        match key.trim() {
            "name" => record.name = Some(value),
            "version" => record.version = Some(value),
            "source" => record.source = Some(value),
            "rev" => record.rev = Some(value),
            "sha256" => record.sha256 = Some(value),
            _ => {}
        }
    }
    if let Some(raw) = current.take() {
        packages.push(raw.into_dep()?);
    }

    packages.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(Lockfile { packages })
}

/// The raw per-`[[package]]` fields collected during the line scan.
#[derive(Default)]
struct RawLocked {
    name: Option<String>,
    version: Option<String>,
    source: Option<String>,
    rev: Option<String>,
    sha256: Option<String>,
}

impl RawLocked {
    /// Turn the collected fields into a typed [`LockedDep`], erroring on a
    /// missing field or a malformed version.
    fn into_dep(self) -> Result<LockedDep, CliError> {
        let missing = |field: &str| {
            CliError::Resolve(format!("ipe.lock: a `[[package]]` is missing `{field}`"))
        };
        let name = self.name.ok_or_else(|| missing("name"))?;
        let version_str = self.version.ok_or_else(|| missing("version"))?;
        let version = semver::Version::parse(&version_str).map_err(|e| {
            CliError::Resolve(format!(
                "ipe.lock: `{version_str}` is not a valid version: {e}"
            ))
        })?;
        Ok(LockedDep {
            name,
            version,
            source: self.source.ok_or_else(|| missing("source"))?,
            rev: self.rev.ok_or_else(|| missing("rev"))?,
            sha256: self.sha256.ok_or_else(|| missing("sha256"))?,
        })
    }
}

/// Strip one layer of surrounding double quotes from a scalar value.
fn unquote(value: &str) -> &str {
    value
        .strip_prefix('"')
        .and_then(|v| v.strip_suffix('"'))
        .unwrap_or(value)
}

#[cfg(test)]
mod tests {
    use super::{LockedDep, Lockfile};
    use std::path::PathBuf;

    fn dep(name: &str, version: &str) -> LockedDep {
        LockedDep {
            name: name.to_owned(),
            version: semver::Version::parse(version).expect("valid version"),
            source: format!("https://example.invalid/{name}"),
            rev: "deadbeef".to_owned(),
            sha256: format!("hash-of-{name}"),
        }
    }

    fn temp_dir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "ipe-lockfile-test-{tag}-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("create temp dir");
        dir
    }

    #[test]
    fn write_then_read_round_trips() {
        let root = temp_dir("roundtrip");
        let mut lock = Lockfile::default();
        lock.upsert(dep("http-extras", "1.2.0"));
        lock.upsert(dep("json-tools", "0.4.1"));
        lock.write(&root).expect("write");

        let read = Lockfile::read(&root).expect("read");
        assert_eq!(read, lock);
        assert_eq!(read.packages().len(), 2);
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn output_is_deterministic_and_sorted() {
        // Insert out of order; both the in-memory order and the rendered text
        // are sorted by name, so a second write is byte-identical.
        let root_a = temp_dir("det-a");
        let root_b = temp_dir("det-b");
        let mut a = Lockfile::default();
        a.upsert(dep("zeta", "1.0.0"));
        a.upsert(dep("alpha", "2.0.0"));
        let mut b = Lockfile::default();
        b.upsert(dep("alpha", "2.0.0"));
        b.upsert(dep("zeta", "1.0.0"));
        a.write(&root_a).expect("write a");
        b.write(&root_b).expect("write b");
        let text_a = std::fs::read_to_string(root_a.join("ipe.lock")).expect("read a");
        let text_b = std::fs::read_to_string(root_b.join("ipe.lock")).expect("read b");
        assert_eq!(text_a, text_b);
        // `alpha` sorts before `zeta` in the rendered file.
        let alpha_at = text_a.find("alpha").expect("alpha present");
        let zeta_at = text_a.find("zeta").expect("zeta present");
        assert!(alpha_at < zeta_at, "packages must be name-sorted");
        let _ = std::fs::remove_dir_all(&root_a);
        let _ = std::fs::remove_dir_all(&root_b);
    }

    #[test]
    fn upsert_replaces_an_existing_entry() {
        let mut lock = Lockfile::default();
        lock.upsert(dep("http-extras", "1.0.0"));
        lock.upsert(dep("http-extras", "1.2.0"));
        assert_eq!(lock.packages().len(), 1);
        let only = lock.packages().first().expect("one package");
        assert_eq!(
            only.version,
            semver::Version::parse("1.2.0").expect("valid")
        );
    }

    #[test]
    fn remove_deletes_and_reports_presence() {
        let mut lock = Lockfile::default();
        lock.upsert(dep("http-extras", "1.0.0"));
        assert!(lock.remove("http-extras"));
        assert!(lock.packages().is_empty());
        assert!(
            !lock.remove("http-extras"),
            "removing an absent dep is false"
        );
    }

    #[test]
    fn a_missing_lockfile_reads_as_empty() {
        let root = temp_dir("absent");
        let lock = Lockfile::read(&root).expect("absent lockfile is empty, not an error");
        assert!(lock.packages().is_empty());
        let _ = std::fs::remove_dir_all(&root);
    }
}
