//! Ipê-owned output directories — the only places the CLI may clean or
//! overwrite.
//!
//! Every build product (`build`, `run`, `watch`, `release`, the `doc` site, the
//! bundle packager) lands inside a directory this module has proven ipe owns.
//! Ownership is explicit on disk: an [`OWNERSHIP_MARKER`] file ipe writes when it
//! creates (or adopts an empty) directory. A directory that already holds
//! anything but carries no marker is user territory and is refused — ipe never
//! cleans, prunes, or overwrites inside it.
//!
//! Two types carry the proof:
//!
//! - [`OwnedDir`] — a directory whose marker is present and which is not a
//!   symlink. The emit pipeline claims one for every crate it writes, so even a
//!   library caller cannot prune a user tree.
//! - [`OutputRoot`] — the CLI's output root (`<project>/out`, or `--out <dir>`),
//!   additionally proven disjoint from the project's sources: it is never the
//!   project root, never an ancestor of it, and never inside the source root.
//!   Products go in fixed subdirectories ([`OutputArea`]) of it, so no product
//!   name can clash with a user file.

use std::io::Read as _;
use std::path::{Component, Path, PathBuf};

use crate::{CliError, io_err};

/// The file whose presence marks a directory as ipe-owned.
pub const OWNERSHIP_MARKER: &str = ".ipe-output";

/// The first line of every [`OWNERSHIP_MARKER`]; a same-named file without it is
/// not proof of ownership.
const MARKER_HEADER: &str = "ipe-output v1";

/// The full marker text written on claim.
const MARKER_TEXT: &str = "ipe-output v1\n\
# This directory is generated by ipe. ipe may overwrite or delete anything in it.\n\
# Keep no hand-written files here; `ipe clean` removes it.\n";

/// Bytes read from a marker to check its header — the marker is tiny, so the
/// read is bounded regardless of what sits at that path.
const MARKER_READ_CAP: u64 = 64;

/// Why a directory was refused as an ipe output location.
#[derive(Debug)]
pub enum OutputRefusal {
    /// The path is a symbolic link; following it could land writes anywhere.
    Symlink(PathBuf),
    /// The path exists but is not a directory.
    NotADirectory(PathBuf),
    /// The directory holds files but no ownership marker: it is user-owned.
    NotIpeOwned(PathBuf),
    /// The output would be the project root itself.
    ProjectRoot(PathBuf),
    /// The output is an ancestor of the project (it would contain the sources).
    ContainsProject {
        /// The refused output path.
        out: PathBuf,
        /// The project root it contains.
        project: PathBuf,
    },
    /// The output lies inside the project's source root.
    InsideSources {
        /// The refused output path.
        out: PathBuf,
        /// The source root it would sit in.
        sources: PathBuf,
    },
    /// A not-yet-existing tail of the path contains `..`, so where it lands
    /// cannot be proven before it is created.
    ParentTraversal(PathBuf),
    /// An ejected project must go to a fresh (absent or empty) directory: the
    /// result is handed to the user, so nothing already there may be replaced.
    NotFresh(PathBuf),
}

impl std::fmt::Display for OutputRefusal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Symlink(p) => write!(
                f,
                "{} is a symbolic link — point --out at a real directory",
                p.display()
            ),
            Self::NotADirectory(p) => write!(f, "{} exists and is not a directory", p.display()),
            Self::NotIpeOwned(p) => write!(
                f,
                "{} already holds files ipe did not create (no `{OWNERSHIP_MARKER}` marker); \
                 ipe never overwrites them — remove the directory yourself or choose another --out",
                p.display()
            ),
            Self::ProjectRoot(p) => write!(
                f,
                "{} is the project root — build output goes in a separate directory \
                 (the default is `out/`)",
                p.display()
            ),
            Self::ContainsProject { out, project } => write!(
                f,
                "{} contains the project at {} — build output must not enclose your sources",
                out.display(),
                project.display()
            ),
            Self::InsideSources { out, sources } => write!(
                f,
                "{} is inside the source root {} — build output must stay out of your sources",
                out.display(),
                sources.display()
            ),
            Self::ParentTraversal(p) => write!(
                f,
                "{} has a `..` in a part that does not exist yet — name the directory directly",
                p.display()
            ),
            Self::NotFresh(p) => write!(
                f,
                "{} is not empty — eject writes a new project, so point --out at an absent \
                 or empty directory",
                p.display()
            ),
        }
    }
}

impl From<OutputRefusal> for CliError {
    fn from(refusal: OutputRefusal) -> Self {
        Self::OutputRefused(refusal)
    }
}

/// A directory proven ipe-owned: not a symlink, and carrying the ownership
/// marker. The only constructor is [`OwnedDir::claim`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OwnedDir(PathBuf);

impl OwnedDir {
    /// Claim `path` for ipe output.
    ///
    /// - Absent: created — with every missing ancestor — and each directory ipe
    ///   creates gets the marker.
    /// - Present, empty: adopted, and the marker written.
    /// - Present with the marker: already ipe's.
    /// - Anything else — a symlink, a file, a non-empty unmarked directory — is
    ///   refused and left untouched.
    ///
    /// # Errors
    /// [`CliError::OutputRefused`] on a refusal; [`CliError::Io`] on a
    /// filesystem failure.
    pub fn claim(path: &Path) -> Result<Self, CliError> {
        if check_claimable(path)? {
            adopt(path)?;
        } else {
            create_marked(path)?;
        }
        Ok(Self(path.to_path_buf()))
    }

    /// The owned directory's path.
    #[must_use]
    pub fn path(&self) -> &Path {
        &self.0
    }

    /// Hand the directory over to the user: remove the ownership marker so ipe
    /// never treats it as its own again (an ejected project becomes user code).
    ///
    /// # Errors
    /// [`CliError::Io`] when the marker cannot be removed.
    pub fn release_to_user(self) -> Result<PathBuf, CliError> {
        let marker = self.0.join(OWNERSHIP_MARKER);
        match std::fs::remove_file(&marker) {
            Ok(()) => Ok(self.0),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(self.0),
            Err(e) => Err(io_err(&marker, e)),
        }
    }
}

/// Decide, without writing, whether `path` may become ipe output: `Ok(false)`
/// when absent, `Ok(true)` when it is a directory that is marked or empty.
///
/// # Errors
/// [`CliError::OutputRefused`] for a symlink, a non-directory, or a non-empty
/// unmarked directory; [`CliError::Io`] on a filesystem failure.
fn check_claimable(path: &Path) -> Result<bool, CliError> {
    match std::fs::symlink_metadata(path) {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(io_err(path, e)),
        Ok(meta) if meta.file_type().is_symlink() => {
            Err(OutputRefusal::Symlink(path.to_path_buf()).into())
        }
        Ok(meta) if !meta.is_dir() => Err(OutputRefusal::NotADirectory(path.to_path_buf()).into()),
        Ok(_) => {
            if has_marker(path)? || is_empty_dir(path)? {
                Ok(true)
            } else {
                Err(OutputRefusal::NotIpeOwned(path.to_path_buf()).into())
            }
        }
    }
}

/// Mark an existing claimable directory (see [`check_claimable`]).
fn adopt(path: &Path) -> Result<(), CliError> {
    if has_marker(path)? {
        Ok(())
    } else {
        write_marker(path)
    }
}

/// Create `path` and each missing ancestor one level at a time, marking every
/// directory created here. An existing ancestor is left as it is; a level that
/// appears concurrently is re-checked as an existing one. The recursion is
/// bounded by the path's component count.
fn create_marked(path: &Path) -> Result<(), CliError> {
    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
        && !check_exists(parent)?
    {
        create_marked(parent)?;
    }
    match std::fs::create_dir(path) {
        Ok(()) => write_marker(path),
        Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => {
            if check_claimable(path)? {
                adopt(path)
            } else {
                Err(io_err(path, e))
            }
        }
        Err(e) => Err(io_err(path, e)),
    }
}

fn check_exists(path: &Path) -> Result<bool, CliError> {
    match std::fs::symlink_metadata(path) {
        Ok(_) => Ok(true),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(io_err(path, e)),
    }
}

/// Whether `dir` carries a genuine ownership marker: a regular file (never a
/// symlink) whose first line is [`MARKER_HEADER`].
///
/// # Errors
/// [`CliError::Io`] on a read failure other than absence.
pub fn has_marker(dir: &Path) -> Result<bool, CliError> {
    let marker = dir.join(OWNERSHIP_MARKER);
    match std::fs::symlink_metadata(&marker) {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(false),
        Err(e) => return Err(io_err(&marker, e)),
        Ok(meta) if !meta.file_type().is_file() => return Ok(false),
        Ok(_) => {}
    }
    let file = std::fs::File::open(&marker).map_err(|e| io_err(&marker, e))?;
    let mut head = Vec::new();
    file.take(MARKER_READ_CAP)
        .read_to_end(&mut head)
        .map_err(|e| io_err(&marker, e))?;
    Ok(head.starts_with(MARKER_HEADER.as_bytes()))
}

/// Write the marker atomically: a uniquely named, exclusively created temp file
/// renamed into place, so a concurrent claimer never reads a half-written
/// marker. The temp name shares the marker prefix, which [`is_empty_dir`]
/// ignores, so a claim in flight never makes the directory look user-owned.
fn write_marker(dir: &Path) -> Result<(), CliError> {
    use std::io::Write as _;
    use std::sync::atomic::{AtomicU64, Ordering};
    static SEQ: AtomicU64 = AtomicU64::new(0);
    let marker = dir.join(OWNERSHIP_MARKER);
    let tmp = dir.join(format!(
        "{OWNERSHIP_MARKER}.{}.{}.tmp",
        std::process::id(),
        SEQ.fetch_add(1, Ordering::Relaxed)
    ));
    let written = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&tmp)
        .and_then(|mut file| file.write_all(MARKER_TEXT.as_bytes()));
    if let Err(e) = written {
        let _ = std::fs::remove_file(&tmp);
        return Err(io_err(&tmp, e));
    }
    if let Err(e) = std::fs::rename(&tmp, &marker) {
        let _ = std::fs::remove_file(&tmp);
        return Err(io_err(&marker, e));
    }
    Ok(())
}

/// Whether `dir` holds nothing but (possibly in-flight) ownership markers.
fn is_empty_dir(dir: &Path) -> Result<bool, CliError> {
    let entries = std::fs::read_dir(dir).map_err(|e| io_err(dir, e))?;
    for entry in entries {
        let entry = entry.map_err(|e| io_err(dir, e))?;
        if !entry
            .file_name()
            .to_string_lossy()
            .starts_with(OWNERSHIP_MARKER)
        {
            return Ok(false);
        }
    }
    Ok(true)
}

/// A fixed product area inside an [`OutputRoot`]. Closed, so every product
/// lands in a name ipe chose.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OutputArea {
    /// The emitted Rust crate (`rust/`).
    Rust,
    /// The runnable development binary (`bin/`).
    Bin,
    /// Production artifacts (`release/`).
    Release,
    /// Packaged desktop / mobile bundles (`dist/`).
    Dist,
    /// The jailed release's app crate (`app/`).
    App,
    /// The jailed release's launcher bundle (`bundle/`).
    Bundle,
}

impl OutputArea {
    /// The area's directory name.
    #[must_use]
    pub const fn dir_name(self) -> &'static str {
        match self {
            Self::Rust => "rust",
            Self::Bin => "bin",
            Self::Release => "release",
            Self::Dist => "dist",
            Self::App => "app",
            Self::Bundle => "bundle",
        }
    }
}

/// The name of the default output root under a project.
pub const DEFAULT_OUTPUT_DIR: &str = "out";

/// The source locations an output root must stay clear of.
#[derive(Debug, Clone)]
pub struct ProjectPaths {
    /// The project root (the `package.ipe` directory, or a single-file entry's
    /// directory).
    root: PathBuf,
    /// The recursive source root of a manifest project; a single-file build
    /// reads only its own directory's files, so it has none.
    sources: Option<PathBuf>,
    /// Where the default `out/` goes: the project root of a manifest project,
    /// the working directory for a single-file build.
    default_base: PathBuf,
}

impl ProjectPaths {
    /// The paths of a manifest project.
    #[must_use]
    pub fn from_manifest(manifest: &crate::project::ProjectManifest) -> Self {
        Self {
            root: manifest.root.clone(),
            sources: Some(manifest.src_root.clone()),
            default_base: manifest.root.clone(),
        }
    }

    /// Derive the project paths for `entry` (a `.ipe` file or a project
    /// directory), reading its `package.ipe` when one is found.
    ///
    /// # Errors
    /// Manifest discovery / parse errors.
    pub fn discover(entry: &Path) -> Result<Self, CliError> {
        if let Some(manifest) = crate::driver::discover_manifest(entry)? {
            let parsed = crate::project::parse_manifest(&manifest)?;
            return Ok(Self::from_manifest(&parsed));
        }
        let root = if entry.is_dir() {
            entry.to_path_buf()
        } else {
            match entry.parent() {
                Some(p) if !p.as_os_str().is_empty() => p.to_path_buf(),
                _ => PathBuf::from("."),
            }
        };
        Ok(Self {
            root,
            sources: None,
            default_base: PathBuf::from("."),
        })
    }
}

/// The CLI's output root, proven disjoint from the project's sources and
/// claimable by ipe. Products go in its [`OutputArea`]s.
///
/// Resolving writes nothing unless the root already exists empty (it is then
/// marked, so the areas created later sit under an owned root). The areas
/// themselves are created — and marked — only when a product is written, so a
/// refused or failed build leaves no directory behind.
#[derive(Debug, Clone)]
pub struct OutputRoot(PathBuf);

impl OutputRoot {
    /// Resolve the output root: `requested` (`--out <dir>`, relative to the
    /// working directory) or the default `out/` (under the project root, or the
    /// working directory for a single-file build).
    ///
    /// # Errors
    /// [`CliError::OutputRefused`] when the path is a symlink, overlaps the
    /// project (its root, an ancestor of it, or inside its source root), or is a
    /// non-empty directory ipe does not own; [`CliError::Io`] on a filesystem
    /// failure.
    pub fn resolve(requested: Option<&str>, project: &ProjectPaths) -> Result<Self, CliError> {
        let raw = requested.map_or_else(
            || project.default_base.join(DEFAULT_OUTPUT_DIR),
            PathBuf::from,
        );
        let checked = check_disjoint(&raw, project)?;
        if check_claimable(&checked)? {
            adopt(&checked)?;
        }
        Ok(Self(checked))
    }

    /// Resolve a fresh directory for a project handed to the user (`ipe eject`):
    /// the same overlap checks as [`OutputRoot::resolve`], and the directory
    /// must be absent or empty — even an ipe-owned populated one is not reused.
    ///
    /// # Errors
    /// As [`OutputRoot::resolve`], plus [`OutputRefusal::NotFresh`].
    pub fn fresh(requested: &str, project: &ProjectPaths) -> Result<Self, CliError> {
        let raw = PathBuf::from(requested);
        let checked = check_disjoint(&raw, project)?;
        if check_exists(&checked)? && !(checked.is_dir() && is_empty_dir(&checked)?) {
            return Err(OutputRefusal::NotFresh(raw).into());
        }
        Ok(Self(checked))
    }

    /// The root directory itself.
    #[must_use]
    pub fn path(&self) -> &Path {
        &self.0
    }

    /// The path of a (possibly nested) product area, e.g. `[Release, Rust]` for
    /// `release/rust`. Every level that already exists is checked claimable — a
    /// symlink or user directory planted at any level is refused — but nothing
    /// is created: the writer claims the area when it writes.
    ///
    /// # Errors
    /// [`CliError::OutputRefused`] for an unclaimable existing level.
    pub fn area_path(&self, areas: &[OutputArea]) -> Result<PathBuf, CliError> {
        let mut path = self.0.clone();
        for area in areas {
            path.push(area.dir_name());
            check_claimable(&path)?;
        }
        Ok(path)
    }

    /// Claim a (possibly nested) product area for writing now.
    ///
    /// # Errors
    /// As [`OutputRoot::area_path`] and [`OwnedDir::claim`].
    pub fn claim_area(&self, areas: &[OutputArea]) -> Result<OwnedDir, CliError> {
        OwnedDir::claim(&self.area_path(areas)?)
    }

    /// Claim the root itself for writing now.
    ///
    /// # Errors
    /// As [`OwnedDir::claim`].
    pub fn claim(&self) -> Result<OwnedDir, CliError> {
        OwnedDir::claim(&self.0)
    }
}

/// Prove `raw` does not overlap `project`, returning the absolute path to claim.
///
/// The final component must not be a symlink. Overlap is decided on resolved
/// paths: the deepest existing ancestor is canonicalised and the not-yet-
/// existing tail appended, which must hold no `..`.
fn check_disjoint(raw: &Path, project: &ProjectPaths) -> Result<PathBuf, CliError> {
    let absolute = absolutize(raw)?;
    if std::fs::symlink_metadata(&absolute).is_ok_and(|m| m.file_type().is_symlink()) {
        return Err(OutputRefusal::Symlink(raw.to_path_buf()).into());
    }
    let resolved = resolve_through_existing(&absolute)
        .ok_or_else(|| OutputRefusal::ParentTraversal(raw.to_path_buf()))?;
    let project_root =
        std::fs::canonicalize(&project.root).map_err(|e| io_err(&project.root, e))?;
    if resolved == project_root {
        return Err(OutputRefusal::ProjectRoot(raw.to_path_buf()).into());
    }
    if project_root.starts_with(&resolved) {
        return Err(OutputRefusal::ContainsProject {
            out: raw.to_path_buf(),
            project: project_root,
        }
        .into());
    }
    if let Some(sources) = &project.sources
        && let Ok(sources) = std::fs::canonicalize(sources)
        && (resolved.starts_with(&sources) || sources.starts_with(&resolved))
    {
        return Err(OutputRefusal::InsideSources {
            out: raw.to_path_buf(),
            sources,
        }
        .into());
    }
    Ok(absolute)
}

fn absolutize(path: &Path) -> Result<PathBuf, CliError> {
    if path.is_absolute() {
        return Ok(path.to_path_buf());
    }
    let cwd = std::env::current_dir().map_err(|e| io_err(Path::new("."), e))?;
    Ok(cwd.join(path))
}

/// Canonicalise the deepest existing ancestor of the absolute `path` and append
/// the rest lexically. `None` when that rest contains `..` (its landing point
/// cannot be proven before it exists).
fn resolve_through_existing(path: &Path) -> Option<PathBuf> {
    let mut existing = path;
    let mut tail: Vec<&std::ffi::OsStr> = Vec::new();
    loop {
        if let Ok(real) = std::fs::canonicalize(existing) {
            let mut resolved = real;
            for part in tail.iter().rev() {
                resolved.push(part);
            }
            return Some(resolved);
        }
        let name = match existing.components().next_back()? {
            Component::Normal(name) => name,
            Component::CurDir => std::ffi::OsStr::new(""),
            Component::ParentDir | Component::RootDir | Component::Prefix(_) => return None,
        };
        if !name.is_empty() {
            tail.push(name);
        }
        existing = existing.parent()?;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("ipe_output_dir_{tag}_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("make scratch");
        std::fs::canonicalize(&dir).expect("canonicalize scratch")
    }

    /// A manifest-shaped project: `<base>/proj/{package.ipe,src/Main.ipe}`.
    fn project(base: &Path) -> ProjectPaths {
        let root = base.join("proj");
        std::fs::create_dir_all(root.join("src")).expect("make src");
        std::fs::write(root.join("package.ipe"), "package proj\n").expect("write manifest");
        std::fs::write(root.join("src").join("Main.ipe"), "module Main\n").expect("write main");
        ProjectPaths {
            root: root.clone(),
            sources: Some(root.join("src")),
            default_base: root.clone(),
        }
    }

    fn user_files_survive(root: &Path) -> bool {
        std::fs::read_to_string(root.join("src").join("Main.ipe"))
            .is_ok_and(|s| s == "module Main\n")
            && root.join("package.ipe").is_file()
    }

    fn refused(result: &Result<OutputRoot, CliError>) -> Option<&OutputRefusal> {
        match result {
            Err(CliError::OutputRefused(refusal)) => Some(refusal),
            _ => None,
        }
    }

    #[test]
    fn default_root_writes_nothing_until_an_area_is_claimed() {
        let base = scratch("default");
        let proj = project(&base);
        let out = OutputRoot::resolve(None, &proj).expect("default out must resolve");
        assert_eq!(out.path(), proj.root.join("out"));
        assert!(!out.path().exists(), "resolving alone creates nothing");

        let rust = out.claim_area(&[OutputArea::Rust]).expect("rust area");
        assert!(
            has_marker(out.path()).expect("root marker"),
            "created root is marked"
        );
        assert!(
            has_marker(rust.path()).expect("area marker"),
            "created area is marked"
        );

        let again = OutputRoot::resolve(None, &proj);
        assert!(again.is_ok(), "an owned root is reusable: {again:?}");
        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn project_root_is_refused() {
        let base = scratch("root");
        let proj = project(&base);
        for raw in [proj.root.clone(), proj.root.join(".")] {
            let result = OutputRoot::resolve(Some(&raw.to_string_lossy()), &proj);
            assert!(
                matches!(refused(&result), Some(OutputRefusal::ProjectRoot(_))),
                "--out {} must be refused, got {result:?}",
                raw.display()
            );
        }
        assert!(user_files_survive(&proj.root));
        assert!(
            !proj.root.join(OWNERSHIP_MARKER).exists(),
            "no marker written"
        );
        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn source_root_and_inside_it_are_refused() {
        let base = scratch("src");
        let proj = project(&base);
        for raw in [proj.root.join("src"), proj.root.join("src").join("gen")] {
            let result = OutputRoot::resolve(Some(&raw.to_string_lossy()), &proj);
            assert!(
                matches!(refused(&result), Some(OutputRefusal::InsideSources { .. })),
                "--out {} must be refused, got {result:?}",
                raw.display()
            );
        }
        assert!(user_files_survive(&proj.root));
        assert!(
            !proj.root.join("src").join("gen").exists(),
            "nothing created in src"
        );
        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn ancestor_of_the_project_is_refused() {
        let base = scratch("ancestor");
        let proj = project(&base);
        for raw in [base.clone(), proj.root.join("src").join("..").join("..")] {
            let result = OutputRoot::resolve(Some(&raw.to_string_lossy()), &proj);
            assert!(
                matches!(
                    refused(&result),
                    Some(OutputRefusal::ContainsProject { .. })
                ),
                "--out {} must be refused, got {result:?}",
                raw.display()
            );
        }
        assert!(user_files_survive(&proj.root));
        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn dot_dot_through_a_missing_tail_is_refused() {
        let base = scratch("dotdot");
        let proj = project(&base);
        let raw = base.join("missing").join("..").join("elsewhere");
        let result = OutputRoot::resolve(Some(&raw.to_string_lossy()), &proj);
        assert!(
            matches!(refused(&result), Some(OutputRefusal::ParentTraversal(_))),
            "an unprovable `..` must be refused, got {result:?}"
        );
        let _ = std::fs::remove_dir_all(&base);
    }

    #[cfg(unix)]
    #[test]
    fn symlinked_out_dir_is_refused_and_its_target_untouched() {
        let base = scratch("symlink");
        let proj = project(&base);
        let victim = base.join("victim");
        std::fs::create_dir_all(&victim).expect("make victim");
        std::fs::write(victim.join("keep.txt"), "keep").expect("write victim file");
        let link = base.join("link");
        std::os::unix::fs::symlink(&victim, &link).expect("make symlink");

        let result = OutputRoot::resolve(Some(&link.to_string_lossy()), &proj);
        assert!(
            matches!(refused(&result), Some(OutputRefusal::Symlink(_))),
            "a symlinked --out must be refused, got {result:?}"
        );
        assert!(victim.join("keep.txt").is_file());
        assert!(
            !victim.join(OWNERSHIP_MARKER).exists(),
            "no marker written through the link"
        );

        // A symlink planted at a product area inside an owned root is refused too,
        // both by the CLI area check and by the emit-level claim.
        let out = OutputRoot::resolve(None, &proj).expect("default out");
        out.claim().expect("claim root");
        std::os::unix::fs::symlink(&victim, out.path().join("rust")).expect("plant area link");
        let area = out.area_path(&[OutputArea::Rust]);
        assert!(
            matches!(
                area,
                Err(CliError::OutputRefused(OutputRefusal::Symlink(_)))
            ),
            "a symlinked area must be refused, got {area:?}"
        );
        let claim = OwnedDir::claim(&out.path().join("rust"));
        assert!(
            matches!(
                claim,
                Err(CliError::OutputRefused(OutputRefusal::Symlink(_)))
            ),
            "the emit-level claim refuses the link too, got {claim:?}"
        );
        assert!(!victim.join(OWNERSHIP_MARKER).exists());
        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn unowned_non_empty_dir_is_never_claimed() {
        let base = scratch("unowned");
        let proj = project(&base);
        let theirs = base.join("theirs");
        std::fs::create_dir_all(&theirs).expect("make dir");
        std::fs::write(theirs.join("notes.txt"), "mine").expect("write user file");

        let result = OutputRoot::resolve(Some(&theirs.to_string_lossy()), &proj);
        assert!(
            matches!(refused(&result), Some(OutputRefusal::NotIpeOwned(_))),
            "a non-empty unmarked dir must be refused, got {result:?}"
        );
        assert!(!theirs.join(OWNERSHIP_MARKER).exists());

        // The emit-level claim refuses it too, and a forged marker is no proof.
        let claim = OwnedDir::claim(&theirs);
        assert!(
            matches!(
                claim,
                Err(CliError::OutputRefused(OutputRefusal::NotIpeOwned(_)))
            ),
            "an unmarked user dir must be refused, got {claim:?}"
        );
        std::fs::write(theirs.join(OWNERSHIP_MARKER), "not a real marker").expect("forge");
        let forged = OwnedDir::claim(&theirs);
        assert!(
            matches!(
                forged,
                Err(CliError::OutputRefused(OutputRefusal::NotIpeOwned(_)))
            ),
            "a forged marker is not ownership, got {forged:?}"
        );
        assert_eq!(
            std::fs::read_to_string(theirs.join("notes.txt"))
                .ok()
                .as_deref(),
            Some("mine")
        );
        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn empty_dir_is_adopted_and_eject_needs_a_fresh_dir() {
        let base = scratch("fresh");
        let proj = project(&base);
        let empty = base.join("empty");
        std::fs::create_dir_all(&empty).expect("make empty");
        let owned = OutputRoot::resolve(Some(&empty.to_string_lossy()), &proj);
        assert!(owned.is_ok(), "an empty dir is adoptable: {owned:?}");
        assert!(has_marker(&empty).expect("marker"), "adoption marks it");

        // Owned but populated — eject still refuses to reuse it.
        std::fs::write(empty.join("main.rs"), "fn main() {}").expect("populate");
        let again = OutputRoot::fresh(&empty.to_string_lossy(), &proj);
        assert!(
            matches!(refused(&again), Some(OutputRefusal::NotFresh(_))),
            "eject must not reuse a populated dir, got {again:?}"
        );

        let new = base.join("ejected");
        let fresh = OutputRoot::fresh(&new.to_string_lossy(), &proj).expect("fresh dir");
        let handed = fresh
            .claim()
            .expect("claim")
            .release_to_user()
            .expect("release");
        assert!(
            !handed.join(OWNERSHIP_MARKER).exists(),
            "handed-over dir is user-owned"
        );
        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn file_at_out_path_is_refused() {
        let base = scratch("file");
        let proj = project(&base);
        let file = base.join("a-file");
        std::fs::write(&file, "data").expect("write file");
        let result = OutputRoot::resolve(Some(&file.to_string_lossy()), &proj);
        assert!(
            matches!(refused(&result), Some(OutputRefusal::NotADirectory(_))),
            "a file at --out must be refused, got {result:?}"
        );
        assert_eq!(std::fs::read_to_string(&file).ok().as_deref(), Some("data"));
        let _ = std::fs::remove_dir_all(&base);
    }
}
