[workspace]
resolver = "2"
members = [
    "crates/sky_intern",
    "crates/sky_diagnostics",
    "crates/sky_kernels",
    "crates/sky_syntax",
    "crates/sky_parse",
    "crates/sky_db",
    "crates/sky_canon",
    "crates/sky_types",
    "crates/sky_ir",
    "crates/sky_lower",
    "crates/sky_backend",
    "crates/sky_backend_rust",
    "crates/sky_watch",
    "crates/skyc",
    "tools/oracle",
    "tools/refresh-oracle",
    "runtime",
    "tools/sky-ffi-inspect-rs",
    "tools/parity-matrix",
]

[workspace.package]
edition = "2024"
version = "0.0.0"
license = "Apache-2.0"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
indexing_slicing = "deny"
unreachable = "deny"
todo = "deny"
unimplemented = "deny"
pedantic = "deny"
nursery = "deny"
