[workspace]
resolver = "2"
members = [
    "src/compiler/ipe_intern",
    "src/compiler/ipe_diagnostics",
    "src/compiler/ipe_kernels",
    "src/compiler/ipe_syntax",
    "src/compiler/ipe_parse",
    "src/compiler/ipe_db",
    "src/compiler/ipe_canon",
    "src/compiler/ipe_types",
    "src/compiler/ipe_ir",
    "src/compiler/ipe_lower",
    "src/compiler/ipe_backend",
    "src/compiler/ipe_backend_rust",
    "src/compiler/ipe_watch",
    "src/ipe-cli",
    "tools/oracle",
    "tools/refresh-oracle",
    "src/runtime/rust",
    "tools/sky-ffi-inspect-rs",
    "tools/parity-matrix",
]

[workspace.package]
edition = "2024"
version = "0.0.0"
license = "Apache-2.0"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
indexing_slicing = "deny"
unreachable = "deny"
todo = "deny"
unimplemented = "deny"
pedantic = "deny"
nursery = "deny"
