#!/usr/bin/env bash
# tools/scripts/gen-sky-lock.sh — write/update examples/sky/upstream.lock.
#
# Computes a per-example content hash of the committed
# examples/sky/original/<name>/ tree for every example listed in
# examples/sky/manifest.toml, then writes (or atomically overwrites)
# examples/sky/upstream.lock.
#
# LOCK FORMAT (plain text, one line per example, sorted by name):
#   <name>\t<64-char-sha256-hex>\n
# Lines that begin with '#' are comments.  The header comment is rewritten
# on every run.
#
# USAGE:
#   tools/scripts/gen-sky-lock.sh           regenerate for all manifest examples
#   tools/scripts/gen-sky-lock.sh --check   verify the committed lock matches;
#                                           exit 1 if any entry differs or is missing
#
# Idempotent: running twice on an unchanged tree produces no diff.
# Exit: 0 ok  1 check-failed / hash-error  2 setup error
set -uo pipefail

source "$(dirname "$0")/lib/env.sh"
source "$(dirname "$0")/lib/mirror.sh"
source "$(dirname "$0")/lib/sky-hash.sh"

cd "$REPO" || { echo "gen-sky-lock: cannot locate repo" >&2; exit 2; }

LOCK="$REPO/examples/sky/upstream.lock"

MODE="write"
while [ $# -gt 0 ]; do
  case "$1" in
    --check) MODE=check ;;
    -h|--help) sed -n '2,15p' "$0"; exit 0 ;;
    *) echo "gen-sky-lock: unknown arg '$1'" >&2; exit 2 ;;
  esac
  shift
done

names="$(sky_example_names)" || { echo "gen-sky-lock: cannot read manifest" >&2; exit 2; }

# Build the lock table: name → hash, for every example that has an
# original/ tree.  Examples without one (e.g. go_ffi examples whose
# original/ was never fetched on this checkout) are skipped with a warning
# rather than failing the whole run — the committed lock entry stays.
declare -A NEW_HASH
errors=0
for name in $names; do
  [ -z "$name" ] && continue
  orig="$REPO/examples/sky/original/$name"
  if [ ! -d "$orig" ]; then
    echo "gen-sky-lock: original/$name missing — skip (run regen-sky-examples.sh first)" >&2
    continue
  fi
  h="$(sky_hash_one "$name")" || { errors=$((errors+1)); continue; }
  NEW_HASH["$name"]="$h"
done
[ "$errors" -gt 0 ] && { echo "gen-sky-lock: $errors hash error(s)" >&2; exit 1; }

if [ "$MODE" = check ]; then
  if [ ! -f "$LOCK" ]; then
    echo "gen-sky-lock --check: upstream.lock missing — run gen-sky-lock.sh" >&2; exit 1
  fi
  drift=0
  # Parse committed lock into committed_hash[name]=hash
  declare -A committed_hash
  while IFS=$'\t' read -r n h; do
    [[ "$n" == \#* ]] && continue
    [ -z "$n" ] && continue
    committed_hash["$n"]="$h"
  done < "$LOCK"
  # Compare
  for name in "${!NEW_HASH[@]}"; do
    ch="${committed_hash[$name]:-}"
    nh="${NEW_HASH[$name]}"
    if [ -z "$ch" ]; then
      echo "gen-sky-lock --check: $name missing from committed upstream.lock" >&2; drift=1
    elif [ "$ch" != "$nh" ]; then
      echo "gen-sky-lock --check: $name hash differs (committed $ch, computed $nh)" >&2; drift=1
    fi
  done
  [ "$drift" = 1 ] && { echo "" >&2; echo "Run: tools/scripts/gen-sky-lock.sh" >&2; exit 1; }
  echo "gen-sky-lock --check: upstream.lock is consistent (${#NEW_HASH[@]} entries)."
  exit 0
fi

# Write mode: sort by name, write atomically.
tmp="$(mktemp "$REPO/examples/sky/upstream.lock.XXXXXX")" || exit 2
{
  echo "# examples/sky/upstream.lock — content hashes of committed original/ trees."
  echo "# Format: <name><TAB><sha256-hex>"
  echo "# Generated by tools/scripts/gen-sky-lock.sh — do not edit by hand."
  for name in $(printf '%s\n' "${!NEW_HASH[@]}" | LC_ALL=C sort); do
    printf '%s\t%s\n' "$name" "${NEW_HASH[$name]}"
  done
} > "$tmp"
mv "$tmp" "$LOCK"
echo "gen-sky-lock: wrote $LOCK (${#NEW_HASH[@]} entries)."
