#!/bin/sh
# Admission sandbox wrapper — Linux x64 / arm64.
#
# Isolation layers (AND-composed, per spec §1.1 redundant-layers):
#   network: seccomp BPF filter injected via `bwrap --seccomp` blocks the
#            socket(2) syscall family. All connect()/socket() calls fail EPERM.
#            `unshare --net` and `bwrap --unshare-net` are both denied by GHA's
#            seccomp policy (CLONE_NEWNET requires CAP_NET_ADMIN on hosted
#            runners), so seccomp is the only available network-denial layer.
#   rootfs:  bubblewrap (bwrap) provides a read-only rootfs bind, isolated
#            pid/uts/ipc namespaces, and a single writable scratch dir.
#
# Seccomp filter: generated by a Python one-liner into a temp file; the filter
# is passed to bwrap as a file descriptor via `--seccomp N`. The filter uses
# SECCOMP_RET_ERRNO(EPERM) on: socket, socketpair, connect, bind, accept,
# accept4, listen, sendto, sendmsg, sendmmsg, recvfrom, recvmsg, recvmmsg.
#
# Fail-closed: if bwrap is absent the script exits non-zero; if the seccomp
# filter cannot be generated the script exits non-zero.

set -eu

FIXTURE="${1:-tests/fixtures/admission/untrusted-build.sh}"
# Use /var/tmp, not /tmp: bwrap mounts --tmpfs /tmp which would hide any
# /tmp/... bind-mount.  /var/tmp survives the --tmpfs /tmp overlay.
SCRATCH="$(mktemp -d /var/tmp/admission-scratch-XXXXXX)"
SECCOMP_FILTER="$(mktemp /var/tmp/admission-seccomp-XXXXXX)"
TIMEOUT_SECS="${ADMISSION_TIMEOUT_SECS:-120}"
# Forwarded into the jail so the enforce run and the unjailed control run target
# the SAME fs-escape path (bwrap makes it read-only via --ro-bind / /).
ESCAPE_PATH="${ESCAPE_PATH:-/usr/jail-escape-probe}"

cleanup() { rm -rf "$SCRATCH" "$SECCOMP_FILTER"; }
trap cleanup EXIT

if ! command -v bwrap >/dev/null 2>&1; then
    echo "ERROR: bubblewrap (bwrap) not found -- cannot establish jail" >&2
    exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: python3 not found -- cannot generate seccomp filter" >&2
    exit 1
fi

FIXTURE_ABS="$(realpath "$FIXTURE")"

# Generate a seccomp BPF filter that blocks socket-related syscalls.
# The filter is a Linux seccomp_filter struct in binary form.
# We use Python's struct module to emit the correct BPF bytecode.
#
# Architecture note: BPF programs run before the syscall and see the
# raw syscall number.  We load the arch word, verify it is the expected
# architecture (x86_64 = 0xC000003E, aarch64 = 0xC00000B7), then load
# the syscall number and deny the socket-family calls with EPERM.
# Any unmatched syscall falls through to ALLOW.
#
# Syscall numbers (x86_64):
#   socket=41, connect=42, accept=43, sendto=44, recvfrom=45,
#   sendmsg=46, recvmsg=47, bind=49, listen=50, accept4=288,
#   sendmmsg=307, recvmmsg=299, socketpair=53
# Syscall numbers (aarch64):
#   socket=198, connect=203, accept=202, sendto=206, recvfrom=207,
#   sendmsg=211, recvmsg=212, bind=200, listen=201, accept4=242,
#   sendmmsg=269, recvmmsg=243, socketpair=199
#
# We emit architecture-specific filters by detecting the running arch.
python3 - "$SECCOMP_FILTER" << 'PYEOF'
import sys, struct, platform

ARCH = platform.machine()

# BPF instruction encoding: struct sock_filter { __u16 code, __u8 jt, __u8 jf, __u32 k }
def ins(code, jt, jf, k):
    return struct.pack('HBBI', code, jt, jf, k)

# BPF opcodes
BPF_LD   = 0x00
BPF_JMP  = 0x05
BPF_RET  = 0x06
BPF_W    = 0x00
BPF_ABS  = 0x20
BPF_JEQ  = 0x10
BPF_K    = 0x00
SECCOMP_RET_ALLOW  = 0x7fff0000
SECCOMP_RET_ERRNO  = 0x00050000  # | errno
EPERM = 1

# seccomp_data offsets
OFF_ARCH    = 4
OFF_NR      = 0

if ARCH in ('x86_64', 'amd64'):
    AUDIT_ARCH = 0xC000003E
    BLOCKED_NRS = [41, 42, 43, 44, 45, 46, 47, 49, 50, 53, 288, 299, 307]
elif ARCH in ('aarch64', 'arm64'):
    AUDIT_ARCH = 0xC00000B7
    BLOCKED_NRS = [198, 199, 200, 201, 202, 203, 206, 207, 211, 212, 242, 243, 269]
else:
    print(f"ERROR: unsupported arch {ARCH}", file=sys.stderr)
    sys.exit(1)

instrs = []
# Load arch word and verify it matches; if not, allow (pass-through to kernel).
arch_ok_offset = 3  # instructions ahead to jump to if arch check fails (see below)
instrs.append(ins(BPF_LD|BPF_W|BPF_ABS, 0, 0, OFF_ARCH))
# jf = offset to ALLOW at end when arch does NOT match (jump over all blockers + RET_ALLOW)
# We'll fix jf after we know total instruction count.
arch_check_idx = len(instrs)
instrs.append(ins(BPF_JMP|BPF_JEQ|BPF_K, 0, 0, AUDIT_ARCH))  # placeholder jf

# Load syscall number.
instrs.append(ins(BPF_LD|BPF_W|BPF_ABS, 0, 0, OFF_NR))

# For each blocked syscall: if nr == X, RET_ERRNO(EPERM).
# jt=0 means: if equal, execute next instruction (RET_ERRNO).
# We emit: JEQ nr jt=0 jf=1, RET_ERRNO; pairs.
for nr in BLOCKED_NRS:
    instrs.append(ins(BPF_JMP|BPF_JEQ|BPF_K, 0, 1, nr))
    instrs.append(ins(BPF_RET|BPF_K, 0, 0, SECCOMP_RET_ERRNO | EPERM))

# Default: allow.
allow_idx = len(instrs)
instrs.append(ins(BPF_RET|BPF_K, 0, 0, SECCOMP_RET_ALLOW))

# Fix up the arch check: jf = number of instructions to skip to reach ALLOW.
jf = allow_idx - arch_check_idx - 1
code, jt, _, k = struct.unpack('HBBI', instrs[arch_check_idx])
instrs[arch_check_idx] = ins(code, jt, jf, k)

# bwrap --seccomp reads the fd as a raw sock_filter array (no length prefix).
# It computes len = file_size / sizeof(sock_filter) and calls
# seccomp(SECCOMP_SET_MODE_FILTER, 0, &prog) with that.
filter_bytes = b''.join(instrs)
count = len(instrs)
out = filter_bytes  # raw array only, no prefix

with open(sys.argv[1], 'wb') as f:
    f.write(out)

print(f"seccomp filter: {count} instructions, arch={ARCH} (0x{AUDIT_ARCH:08X}), blocking {len(BLOCKED_NRS)} syscall numbers")
PYEOF

# Verify the filter was generated.
if [ ! -s "$SECCOMP_FILTER" ]; then
    echo "ERROR: seccomp filter file is empty -- cannot establish network isolation" >&2
    exit 1
fi

# Open the seccomp filter file on fd 4 and pass it to bwrap.
# bwrap --seccomp N reads the filter from fd N.
exec 4< "$SECCOMP_FILTER"

# Bind scratch at its real host path (not /scratch) because --ro-bind / /
# makes the root read-only and bwrap cannot mkdir /scratch over it.
# --bind src dst requires dst to already exist in the sandbox; binding at
# the same path as on the host means the directory already exists via
# --ro-bind / /.
timeout "$TIMEOUT_SECS" \
    bwrap \
        --ro-bind / / \
        --bind "$SCRATCH" "$SCRATCH" \
        --tmpfs /tmp \
        --proc /proc \
        --dev /dev \
        --unshare-pid \
        --unshare-uts \
        --unshare-ipc \
        --die-with-parent \
        --seccomp 4 \
        --setenv SCRATCH_DIR "$SCRATCH" \
        --setenv ESCAPE_PATH "$ESCAPE_PATH" \
        sh "$FIXTURE_ABS"
