[package]
name = "sky_canon"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
sky_intern = { path = "../sky_intern" }
sky_diagnostics = { path = "../sky_diagnostics" }
sky_syntax = { path = "../sky_syntax" }
sky_kernels = { path = "../sky_kernels" }

[dev-dependencies]
sky_parse = { path = "../sky_parse" }

[lints]
workspace = true
