// Generated by Sky compiler (Rust target)
#![allow(unused, non_snake_case)]

#[cfg(feature = "static_alloc")]
#[global_allocator]
static SKY_GLOBAL_ALLOC: mimalloc::MiMalloc = mimalloc::MiMalloc;

pub mod sky_runtime;
pub use sky_runtime::*;

use std::collections::BTreeSet;
use std::collections::HashMap;
use std::fmt;
use std::future::ready;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;
use std::task::{Context, Poll, Wake, Waker};

// Basic types
type SkyInt = i64;
type SkyFloat = f64;
type SkyBool = bool;
type SkyString = String;
type Value = JsonVal;

// ===========================================
// USER TYPES
// ===========================================

#[derive(Clone, Debug, PartialEq)]
pub struct RecXY {
    x: i64,
    y: i64,
}
impl SkyStringify for RecXY {
    fn sky_show(&self) -> String {
        format!("{{{} {}}}", (&sky_runtime::stringify::Wrap(&self.x)).dispatch(), (&sky_runtime::stringify::Wrap(&self.y)).dispatch())
    }
}

type SkyError = String;
pub fn str_err(s: &str) -> SkyError {
    s.to_string()
}

pub type SkyTask<A> = sky_runtime::SkyTask<SkyError, A>;
pub type Decoder<T> = sky_runtime::json::Decoder<SkyError, T>;

pub fn ok_res<A>(a: A) -> SkyResult<SkyError, A> {
    sky_runtime::core::ok_res(a)
}
pub fn task_succeed<A: Send + 'static>(a: A) -> SkyTask<A> {
    sky_runtime::task::task_succeed(a)
}
pub fn log_info(msg: String) -> SkyTask<()> {
    sky_runtime::log::log_info(msg)
}
pub fn log_debug(msg: String) -> SkyTask<()> {
    sky_runtime::log::log_debug(msg)
}
pub fn log_warn(msg: String) -> SkyTask<()> {
    sky_runtime::log::log_warn(msg)
}
pub fn log_error(msg: String) -> SkyTask<()> {
    sky_runtime::log::log_error(msg)
}
pub fn log_println(msg: String) -> SkyTask<()> {
    sky_runtime::log::log_println(msg)
}
pub fn log_info_with<A: SkyStringify>(msg: String, attrs: Vec<A>) -> SkyTask<()> {
    sky_runtime::log::log_info_with(msg, attrs)
}
pub fn log_error_with<A: SkyStringify>(msg: String, attrs: Vec<A>) -> SkyTask<()> {
    sky_runtime::log::log_error_with(msg, attrs)
}
pub fn log_debug_with<A: SkyStringify>(msg: String, attrs: Vec<A>) -> SkyTask<()> {
    sky_runtime::log::log_debug_with(msg, attrs)
}
pub fn log_warn_with<A: SkyStringify>(msg: String, attrs: Vec<A>) -> SkyTask<()> {
    sky_runtime::log::log_warn_with(msg, attrs)
}
pub fn system_args(_: ()) -> SkyTask<Vec<String>> {
    sky_runtime::system::system_args(())
}
pub fn system_setenv(key: String, val: String) -> SkyTask<()> {
    sky_runtime::system::system_setenv(key, val)
}
pub fn system_unsetenv(key: String) -> SkyTask<()> {
    sky_runtime::system::system_unsetenv(key)
}
pub fn time_now(_: ()) -> SkyTask<i64> {
    sky_runtime::time::time_now(())
}
pub fn time_sleep(ms: i64) -> SkyTask<()> {
    sky_runtime::time::time_sleep(ms)
}
pub fn time_unix_millis(_: ()) -> SkyTask<i64> {
    sky_runtime::time::time_unix_millis(())
}
pub fn random_int(lo: i64, hi: i64) -> SkyTask<i64> {
    sky_runtime::random::random_int(lo, hi)
}
pub fn random_float(lo: f64, hi: f64) -> SkyTask<f64> {
    sky_runtime::random::random_float(lo, hi)
}
pub fn random_choice(items: Vec<String>) -> SkyTask<String> {
    sky_runtime::random::random_choice(items)
}
pub fn file_read_file(path: String) -> SkyTask<String> {
    sky_runtime::file::file_read_file(path)
}
pub fn file_write_file(path: String, content: String) -> SkyTask<()> {
    sky_runtime::file::file_write_file(path, content)
}
pub fn file_delete(path: String) -> SkyTask<()> {
    sky_runtime::file::file_delete(path)
}
pub fn crypto_random_bytes(n: i64) -> SkyTask<String> {
    sky_runtime::crypto::crypto_random_bytes(n)
}
pub fn crypto_random_token(n: i64) -> SkyTask<String> {
    sky_runtime::crypto::crypto_random_token(n)
}

pub fn sky_main() -> SkyTask<()> {
    ({ let p = RecXY { x: 1, y: 2 }; ({ let q = { let mut __sky_rec = (p).clone(); __sky_rec.x = 41; __sky_rec }; log_println(string_from_int(((q).x + (p).y))) }) })
}

// Ffi.kernel polyfill — should be unreachable in Rust target;
// the codegen routes Ffi.kernel calls directly, but some construction
// paths (e.g. inline let-bindings of Ffi.kernel) leave a residual call.
#[allow(unreachable_code)]
fn ffi_kernel_polyfill<T>(_name: String) -> T {
    panic!("Ffi.kernel '{}' should not be called in Rust target", _name)
}

// List helpers
pub fn list_map_consume<T0, T1>(f: impl Fn(T0) -> T1, list: Vec<T0>) -> Vec<T1> {
    list.into_iter().map(f).collect()
}

// ===========================================
// FFI PLACEHOLDER TYPES (types referenced but not defined)
// ===========================================

// ===========================================
// ENTRY POINT
// ===========================================

fn main() {
    // Synchronous-panic gate (Go parity: rt.LogPanicAndExit) —
    // classify an escaping panic (div-by-zero / index-OOB /
    // overflow) into a Sky error + exit 1, not a raw Rust backtrace.
    sky_runtime::core::install_panic_classifier();
    match block_on(sky_main()) {
        SkyResult::Ok(_) => (),
        SkyResult::Err(e) => {
            eprintln!("{:?}", e);
            std::process::exit(1);
        }
    }
}
