[package]
name = "ipe_canon"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
ipe_intern = { path = "../ipe_intern" }
ipe_diagnostics = { path = "../ipe_diagnostics" }
ipe_syntax = { path = "../ipe_syntax" }
ipe_kernels = { path = "../ipe_kernels" }

[dev-dependencies]
ipe_parse = { path = "../ipe_parse" }

[lints]
workspace = true
