name = "05-mux-server"
version = "0.1.0"
entry = "src/Main.sky"
port = 8000

["go.dependencies"]
"github.com/gorilla/mux" = "latest"
"github.com/joho/godotenv" = "latest"
"net/http" = "latest"
"os" = "latest"
"io" = "latest"
