[package]
name = "ipe_lower"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
ipe_intern = { path = "../ipe_intern" }
ipe_diagnostics = { path = "../ipe_diagnostics" }
ipe_canon = { path = "../ipe_canon" }
ipe_types = { path = "../ipe_types" }
ipe_ir = { path = "../ipe_ir" }

[dev-dependencies]
ipe_parse = { path = "../ipe_parse" }

[lints]
workspace = true
