#!/usr/bin/env bash
# Build the in-browser Ipê compiler (the `ipe-wasm` frontend crate) and generate
# the wasm-bindgen JS glue into ./pkg/, which index.html loads directly.
#
# Output (./pkg/) is a build artifact — gitignored, regenerated by this script.
# Requires: the `wasm32-unknown-unknown` rustup target and the `wasm-bindgen`
# CLI (`cargo install wasm-bindgen-cli`, version matching the crate).
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$here/../.." && pwd)"

# Honour a caller-provided CARGO_TARGET_DIR; otherwise use cargo's default.
target_dir="${CARGO_TARGET_DIR:-$repo_root/target}"

echo "Building ipe-wasm for wasm32-unknown-unknown (release)…"
( cd "$repo_root" && cargo build -p ipe-wasm --target wasm32-unknown-unknown --release )

wasm_in="$target_dir/wasm32-unknown-unknown/release/ipe_wasm.wasm"
echo "Generating JS bindings with wasm-bindgen…"
wasm-bindgen \
  --target web \
  --no-typescript \
  --out-dir "$here/pkg" \
  --out-name ipe_wasm \
  "$wasm_in"

echo "Done. Serve this directory over HTTP with any static file server, e.g.:"
echo "  npx serve \"$here\""
echo "or"
echo "  miniserve \"$here\""
echo "then open the URL it prints (the module + WASM must be fetched over HTTP,"
echo "not file://)."
