//! Fixed Rust-target templates emitted verbatim for every program.
//!
//! The Ipê → Rust codegen wraps the user's emitted types and functions in a
//! fixed prologue (header, imports, basic type aliases, runtime re-exports) and
//! a fixed epilogue (`Ffi.kernel` polyfill, list helpers, FFI-placeholder
//! banner, entry point). Those two fixed regions are produced here.
//!
//! The byte source of truth is the hand-maintained template at
//! `templates/main.rs` — a canonical whole-program rendering that owns the fixed
//! prologue and epilogue verbatim. The emitter slices those two fixed regions
//! out of the embedded template at well-defined textual anchors. This template
//! is NOT a golden fixture: no `tests/golden/*` file is an input to codegen, so
//! every golden (including `basics`) can be regenerated by the very compiler
//! that embeds this template. The crate's tests assert byte equality against an
//! independent, line-number-based reconstruction of the same template, so any
//! anchor mistake is caught.
//!
//! A missing anchor is not a silent empty fallback: a template edit
//! that drops the USER TYPES banner or the `Ffi.kernel` polyfill comment fails
//! loudly with [`Diagnostic::CompilerBug`] (IPE-I0203) rather than emitting a
//! truncated project.

use ipe_diagnostics::{DResult, Diagnostic};

/// The canonical template, embedded at compile time. The fixed preamble and
/// epilogue are exact substrings of this file.
const GOLDEN: &str = include_str!("../templates/main.rs");

/// The `Diagnostic::CompilerBug` raised when a template anchor is absent — a
/// drifted-template invariant violation, surfaced (IPE-I0203) instead of a
/// silent empty slice.
fn anchor_missing(anchor: &str) -> Diagnostic {
    Diagnostic::CompilerBug {
        where_: "backend.golden_anchor",
        detail: format!("template anchor {anchor:?} not found in the embedded emit template"),
    }
}

/// The fixed prologue emitted before the user's type and function definitions.
///
/// Spans the golden header, file-level attributes, runtime re-exports, imports,
/// basic type aliases, and the `// USER TYPES` section banner — everything up to
/// (and not including) the first user type definition.
///
/// `keep_json` keeps the `type Value = JsonVal;` basic-type alias; when `false`
/// (a program that names neither `Value` nor `Decoder`, i.e. `!reaches_json`) the
/// alias is cut, so the preamble never spells `JsonVal` — a type re-exported from
/// the `json` runtime module only when the `json` feature is on. The companion
/// `pub type Decoder<T> = …` alias, which lives in the kernel-wrapper prelude, is
/// cut on the SAME flag by [`crate::project`]'s `native_runtime_bindings`.
///
/// # Errors
///
/// Returns [`Diagnostic::CompilerBug`] (IPE-I0203) if the USER TYPES banner
/// anchor — or, when cutting it, the `type Value` alias — is absent from the
/// embedded golden.
pub fn preamble(keep_json: bool) -> DResult<String> {
    // The user type definitions begin immediately after the USER TYPES banner
    // block, which is `// USER TYPES` followed by the banner's closing `// ===`
    // rule and a single blank line. Cut at the blank line that terminates the
    // banner so the preamble owns the whole banner and the user types follow.
    const BANNER_TITLE: &str = "// USER TYPES\n";
    // The `Value` basic-type alias, cut for a `!keep_json` program (see below).
    const VALUE_ALIAS: &str = "type Value = JsonVal;\n";
    let title_idx = GOLDEN
        .find(BANNER_TITLE)
        .ok_or_else(|| anchor_missing(BANNER_TITLE))?;
    let rest = GOLDEN
        .get(title_idx..)
        .ok_or_else(|| anchor_missing(BANNER_TITLE))?;
    // The first blank line after the title closes the banner; include it.
    let blank = rest
        .find("\n\n")
        .ok_or_else(|| anchor_missing(BANNER_TITLE))?;
    let end = title_idx + blank + "\n\n".len();
    let text = GOLDEN
        .get(..end)
        .map(str::to_owned)
        .ok_or_else(|| anchor_missing(BANNER_TITLE))?;
    if keep_json {
        return Ok(text);
    }
    // Cut the `Value` alias for a program that reaches no `json`. Content-addressed
    // on the whole line so a golden drift that renamed it fails loud rather than
    // silently leaving a `JsonVal` reference the dropped `json` feature can't
    // resolve (E0412).
    if !text.contains(VALUE_ALIAS) {
        return Err(anchor_missing(VALUE_ALIAS));
    }
    Ok(text.replace(VALUE_ALIAS, ""))
}

/// The fixed epilogue emitted after the user's function definitions.
///
/// Spans the `Ffi.kernel` polyfill, the list helpers, the FFI-placeholder
/// banner, and the entry point (`fn main`) — the tail of the golden program.
///
/// # Errors
///
/// Returns [`Diagnostic::CompilerBug`] (IPE-I0203) if the `Ffi.kernel` polyfill
/// anchor is absent from the embedded golden.
pub fn epilogue() -> DResult<String> {
    // Anchored on the ASCII prefix of the polyfill comment (the full comment
    // contains a UTF-8 em-dash; the prefix is unique and ASCII-only).
    const ANCHOR: &str = "// Ffi.kernel polyfill";
    let start = GOLDEN.find(ANCHOR).ok_or_else(|| anchor_missing(ANCHOR))?;
    GOLDEN
        .get(start..)
        .map(str::to_owned)
        .ok_or_else(|| anchor_missing(ANCHOR))
}

#[cfg(test)]
mod tests {
    use super::{epilogue, preamble};
    use ipe_diagnostics::DResult;

    /// Independent copy of the template, reconstructed by 1-indexed line ranges
    /// so the assertions don't merely echo the implementation's anchor logic.
    const GOLDEN: &str = include_str!("../templates/main.rs");

    #[test]
    fn preamble_matches_golden_lines_1_to_34() -> DResult<()> {
        // Lines 1..=34: header (incl. the cfg-gated allocator arms) through the
        // blank line closing the USER TYPES banner (the next line, 35, is the
        // first user type definition). The golden template is a JSON-using program,
        // so `keep_json` reproduces it verbatim (the `type Value` alias present).
        let expected: String = GOLDEN.split_inclusive('\n').take(34).collect();
        assert_eq!(preamble(true)?, expected);
        Ok(())
    }

    #[test]
    fn preamble_drops_value_alias_when_no_json() -> DResult<()> {
        // A program that reaches no `json` cuts the `type Value = JsonVal;` alias
        // so the preamble never spells `JsonVal` (unresolved once `json` is
        // dropped). Every other preamble line is preserved.
        let kept = preamble(true)?;
        let dropped = preamble(false)?;
        assert!(
            kept.contains("type Value = JsonVal;\n"),
            "the json-keeping preamble carries the `Value` alias"
        );
        assert!(
            !dropped.contains("JsonVal"),
            "the json-dropping preamble names no JsonVal: {dropped:?}"
        );
        assert_eq!(
            dropped,
            kept.replace("type Value = JsonVal;\n", ""),
            "dropping json removes ONLY the `Value` alias line"
        );
        Ok(())
    }

    #[test]
    fn epilogue_matches_golden_lines_277_to_end() -> DResult<()> {
        // Lines 277..=end: the `Ffi.kernel` polyfill through `fn main`. (The
        // `Crypto (entropy)` prelude section header added ahead of the
        // `crypto_random_*` wrappers shifted the polyfill down one line.)
        let expected: String = GOLDEN.split_inclusive('\n').skip(276).collect();
        assert_eq!(epilogue()?, expected);
        Ok(())
    }

    #[test]
    fn preamble_is_a_prefix_of_golden() -> DResult<()> {
        assert!(GOLDEN.starts_with(&preamble(true)?));
        Ok(())
    }

    #[test]
    fn epilogue_is_a_suffix_of_golden() -> DResult<()> {
        assert!(GOLDEN.ends_with(&epilogue()?));
        Ok(())
    }

    #[test]
    fn preamble_ends_with_user_types_banner() -> DResult<()> {
        assert!(
            preamble(true)?
                .ends_with("// USER TYPES\n// ===========================================\n\n")
        );
        Ok(())
    }

    #[test]
    fn epilogue_starts_with_polyfill_and_ends_with_main() -> DResult<()> {
        assert!(epilogue()?.starts_with("// Ffi.kernel polyfill"));
        assert!(epilogue()?.trim_end().ends_with('}'));
        Ok(())
    }
}
