// Generated by Sky compiler (Rust target)
#![allow(unused, non_snake_case)]

#[cfg(feature = "static_alloc")]
#[global_allocator]
static IPE_GLOBAL_ALLOC: mimalloc::MiMalloc = mimalloc::MiMalloc;

pub mod sky_runtime;
pub use sky_runtime::*;

use std::collections::BTreeSet;
use std::collections::HashMap;
use std::fmt;
use std::future::ready;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;
use std::task::{Context, Poll, Wake, Waker};

// Basic types
type SkyInt = i64;
type SkyFloat = f64;
type SkyBool = bool;
type SkyString = String;
type Value = JsonVal;

// ===========================================
// USER TYPES
// ===========================================

#[derive(Clone, Debug, PartialEq)]
pub enum MainMsg {
    Increment,
    Decrement,
}
impl SkyStringify for MainMsg {
    fn sky_show(&self) -> String {
        match self {
            MainMsg::Increment => "Increment".to_string(),
            MainMsg::Decrement => "Decrement".to_string(),
        }
    }
}

pub use sky_runtime::error::SkyError;
pub fn str_err(s: &str) -> SkyError {
    SkyError::unexpected(s.to_string())
}

pub type SkyTask<A> = sky_runtime::SkyTask<SkyError, A>;
pub type Decoder<T> = sky_runtime::json::Decoder<SkyError, T>;

pub fn ok_res<A>(a: A) -> SkyResult<SkyError, A> {
    sky_runtime::core::ok_res(a)
}
pub fn task_succeed<A: Send + 'static>(a: A) -> SkyTask<A> {
    sky_runtime::task::task_succeed(a)
}
pub fn log_info(msg: String) -> SkyTask<()> {
    sky_runtime::log::log_info(msg)
}
pub fn log_debug(msg: String) -> SkyTask<()> {
    sky_runtime::log::log_debug(msg)
}
pub fn log_warn(msg: String) -> SkyTask<()> {
    sky_runtime::log::log_warn(msg)
}
pub fn log_error(msg: String) -> SkyTask<()> {
    sky_runtime::log::log_error(msg)
}
pub fn log_println(msg: String) -> SkyTask<()> {
    sky_runtime::log::log_println(msg)
}
pub fn log_info_with<A: SkyStringify>(msg: String, attrs: Vec<A>) -> SkyTask<()> {
    sky_runtime::log::log_info_with(msg, attrs)
}
pub fn log_error_with<A: SkyStringify>(msg: String, attrs: Vec<A>) -> SkyTask<()> {
    sky_runtime::log::log_error_with(msg, attrs)
}
pub fn log_debug_with<A: SkyStringify>(msg: String, attrs: Vec<A>) -> SkyTask<()> {
    sky_runtime::log::log_debug_with(msg, attrs)
}
pub fn log_warn_with<A: SkyStringify>(msg: String, attrs: Vec<A>) -> SkyTask<()> {
    sky_runtime::log::log_warn_with(msg, attrs)
}
pub fn system_args(_: ()) -> SkyTask<Vec<String>> {
    sky_runtime::system::system_args(())
}
pub fn system_setenv(key: String, val: String) -> SkyTask<()> {
    sky_runtime::system::system_setenv(key, val)
}
pub fn system_unsetenv(key: String) -> SkyTask<()> {
    sky_runtime::system::system_unsetenv(key)
}
pub fn time_now(_: ()) -> SkyTask<i64> {
    sky_runtime::time::time_now(())
}
pub fn time_sleep(ms: i64) -> SkyTask<()> {
    sky_runtime::time::time_sleep(ms)
}
pub fn time_unix_millis(_: ()) -> SkyTask<i64> {
    sky_runtime::time::time_unix_millis(())
}
pub fn random_int(lo: i64, hi: i64) -> SkyTask<i64> {
    sky_runtime::random::random_int(lo, hi)
}
pub fn random_float(lo: f64, hi: f64) -> SkyTask<f64> {
    sky_runtime::random::random_float(lo, hi)
}
pub fn random_choice(items: Vec<String>) -> SkyTask<String> {
    sky_runtime::random::random_choice(items)
}
pub fn file_read_file(path: String) -> SkyTask<String> {
    sky_runtime::file::file_read_file(path)
}
pub fn file_write_file(path: String, content: String) -> SkyTask<()> {
    sky_runtime::file::file_write_file(path, content)
}
pub fn file_delete(path: String) -> SkyTask<()> {
    sky_runtime::file::file_delete(path)
}
// ── Task combinators (M5a) ─────────────────────────────────────────────────
pub fn task_fail<A: Send + 'static>(e: SkyError) -> SkyTask<A> {
    sky_runtime::task::task_fail(e)
}
pub fn task_map<A: Send + 'static, B: Send + 'static>(
    f: Box<dyn Fn(A) -> B + Send + 'static>,
    t: SkyTask<A>,
) -> SkyTask<B> {
    sky_runtime::task::task_map(f, t)
}
pub fn task_and_then<A: Send + 'static, B: Send + 'static>(
    t: SkyTask<A>,
    f: Box<dyn FnOnce(A) -> SkyTask<B> + Send + 'static>,
) -> SkyTask<B> {
    sky_runtime::task::task_and_then(t, f)
}
pub fn task_map_error<A: Send + 'static>(
    f: Box<dyn Fn(SkyError) -> SkyError + Send + 'static>,
    t: SkyTask<A>,
) -> SkyTask<A> {
    sky_runtime::task::task_map_error(f, t)
}
pub fn task_on_error<A: Send + 'static>(
    f: Box<dyn FnOnce(SkyError) -> SkyTask<A> + Send + 'static>,
    t: SkyTask<A>,
) -> SkyTask<A> {
    sky_runtime::task::task_on_error(f, t)
}
pub fn task_from_result<A: Send + 'static>(r: SkyResult<SkyError, A>) -> SkyTask<A> {
    sky_runtime::task::task_from_result(r)
}
pub fn task_and_then_result<A: Send + 'static, B: Send + 'static>(
    f: Box<dyn Fn(A) -> SkyResult<SkyError, B> + Send + 'static>,
    t: SkyTask<A>,
) -> SkyTask<B> {
    sky_runtime::task::task_and_then_result(f, t)
}
pub fn task_sequence<A: Send + 'static>(tasks: Vec<SkyTask<A>>) -> SkyTask<Vec<A>> {
    sky_runtime::task::task_sequence(tasks)
}
pub fn task_parallel<A: Send + 'static>(tasks: Vec<SkyTask<A>>) -> SkyTask<Vec<A>> {
    sky_runtime::task::task_parallel(tasks)
}
pub fn task_run<A: Send + 'static>(t: SkyTask<A>) -> SkyResult<SkyError, A> {
    sky_runtime::task::task_run(t)
}
// ── Io kernels (M5a) ───────────────────────────────────────────────────────
pub fn io_read_line(_: ()) -> SkyTask<String> {
    sky_runtime::io::io_read_line(())
}
pub fn io_write_stdout(s: String) -> SkyTask<()> {
    sky_runtime::io::io_write_stdout(s)
}
pub fn io_write_stderr(s: String) -> SkyTask<()> {
    sky_runtime::io::io_write_stderr(s)
}
// ── System kernels (M5a) ───────────────────────────────────────────────────
pub fn system_getenv(key: String) -> SkyTask<String> {
    sky_runtime::system::system_getenv(key)
}
pub fn system_getenv_or(key: String, default: String) -> String {
    sky_runtime::system::system_getenv_or(key, default)
}
pub fn system_get_arg(n: i64) -> SkyTask<SkyMaybe<String>> {
    sky_runtime::system::system_get_arg(n)
}
pub fn system_getenv_int(key: String) -> SkyTask<i64> {
    sky_runtime::system::system_getenv_int(key)
}
pub fn system_getenv_bool(key: String) -> SkyTask<bool> {
    sky_runtime::system::system_getenv_bool(key)
}
pub fn system_cwd(_: ()) -> SkyTask<String> {
    sky_runtime::system::system_cwd(())
}
pub fn system_load_env(_: ()) -> SkyTask<()> {
    sky_runtime::system::system_load_env(())
}
pub fn system_exit(code: i64) -> ! {
    sky_runtime::system::system_exit(code)
}
// ── File kernels (M5a) ─────────────────────────────────────────────────────
pub fn file_exists(path: String) -> SkyTask<bool> {
    sky_runtime::file::file_exists(path)
}
pub fn file_remove(path: String) -> SkyTask<()> {
    sky_runtime::file::file_remove(path)
}
pub fn file_mkdir_all(path: String) -> SkyTask<()> {
    sky_runtime::file::file_mkdir_all(path)
}
pub fn file_read_file_limit(path: String, limit: i64) -> SkyTask<String> {
    sky_runtime::file::file_read_file_limit(path, limit)
}
pub fn file_read_file_bytes(path: String) -> SkyTask<Vec<i64>> {
    sky_runtime::file::file_read_file_bytes(path)
}
pub fn file_append(path: String, content: String) -> SkyTask<()> {
    sky_runtime::file::file_append(path, content)
}
pub fn file_read_dir(path: String) -> SkyTask<Vec<String>> {
    sky_runtime::file::file_read_dir(path)
}
pub fn file_is_dir(path: String) -> SkyTask<bool> {
    sky_runtime::file::file_is_dir(path)
}
pub fn file_temp_file(prefix: String) -> SkyTask<String> {
    sky_runtime::file::file_temp_file(prefix)
}
pub fn file_temp_dir(prefix: String) -> SkyTask<String> {
    sky_runtime::file::file_temp_dir(prefix)
}
pub fn file_copy(src: String, dst: String) -> SkyTask<()> {
    sky_runtime::file::file_copy(src, dst)
}
pub fn file_rename(src: String, dst: String) -> SkyTask<()> {
    sky_runtime::file::file_rename(src, dst)
}
pub fn crypto_random_bytes(n: i64) -> SkyTask<String> {
    sky_runtime::crypto::crypto_random_bytes(n)
}
pub fn crypto_random_token(n: i64) -> SkyTask<String> {
    sky_runtime::crypto::crypto_random_token(n)
}
// ── Http kernels (M5b) ─────────────────────────────────────────────────────
pub fn http_parse_query(raw: String) -> HashMap<String, String> {
    sky_runtime::http_client::http_parse_query(raw)
}

pub fn main_update(msg: MainMsg, count: i64) -> i64 {
    match msg {
        MainMsg::Increment => (count + 1),
        MainMsg::Decrement => (count - 1),
    }
}
pub fn sky_main() -> SkyTask<()> {
    log_println(string_from_int(main_update(MainMsg::Increment, 0)))
}

// Ffi.kernel polyfill — should be unreachable in Rust target;
// the codegen routes Ffi.kernel calls directly, but some construction
// paths (e.g. inline let-bindings of Ffi.kernel) leave a residual call.
#[allow(unreachable_code)]
fn ffi_kernel_polyfill<T>(_name: String) -> T {
    panic!("Ffi.kernel '{}' should not be called in Rust target", _name)
}

// List helpers
pub fn list_map_consume<T0, T1>(f: impl Fn(T0) -> T1, list: Vec<T0>) -> Vec<T1> {
    list.into_iter().map(f).collect()
}

// ===========================================
// FFI PLACEHOLDER TYPES (types referenced but not defined)
// ===========================================

// ===========================================
// ENTRY POINT
// ===========================================

fn main() {
    // Synchronous-panic gate (Go parity: rt.LogPanicAndExit) —
    // classify an escaping panic (div-by-zero / index-OOB /
    // overflow) into a Sky error + exit 1, not a raw Rust backtrace.
    sky_runtime::core::install_panic_classifier();
    match block_on(sky_main()) {
        SkyResult::Ok(_) => (),
        SkyResult::Err(e) => {
            eprintln!("{:?}", e);
            std::process::exit(1);
        }
    }
}
