//! The Tier-2 link-reachability probe emitter.
//!
//! Tier-2 admission ([`crate::audit_native`] in `ipe-cli`, ADR 0046) must build
//! and link a native-bearing package's OWN foreign surface under a jail scoped
//! to its declared capability set, so a build-time capability reach (a
//! `build.rs`, proc-macro, linker script, or `bindgen` fetch inside a bound
//! crate) is observed as a denial. Linking alone under-observes: the linker
//! dead-strips any wrapper nothing references, taking that wrapper's transitive
//! foreign call — and its build-time reach — with it.
//!
//! This module emits a probe `main` that REFERENCES every surviving wrapper so
//! the linker must retain the whole foreign surface. The reference is an
//! address-of into an opaque sink ([`std::hint::black_box`]); the probe NEVER
//! invokes a wrapper with fabricated inputs — that would run unbounded author
//! logic and cannot synthesise a valid opaque receiver anyway. What is confined
//! is the *build and link* of the package's real surface, never a stand-in whose
//! actions Tier-2 chose.
//!
//! ## Single source of the exercised surface
//!
//! The referenced set is exactly [`crate::bindings::surviving_ref_names`] — the
//! SAME survivor gate the interface emitter keys off — mapped through the SAME
//! [`crate::naming::wrapper_fn_ident`] the emitted `_bindings.rs` names its
//! `pub fn`s with. So the probe's surface cannot drift from the package's real
//! emitted surface, and the package cannot author a narrower probe: it does not
//! write the probe at all.

use crate::pkginfo::PkgInfo;

/// The fully-qualified path of every surviving wrapper `pub fn` for one bound
/// crate, in the emitted app crate's module tree.
///
/// Each emitted `_bindings.rs` becomes `pub mod <slug> { … }` under the app
/// crate's `crate::ffi`, so a wrapper `pub fn <ident>` is reachable at
/// `crate::ffi::<slug>::<ident>`. The `<ident>` is derived by the SAME
/// [`crate::naming::wrapper_fn_ident`] the emitter uses, keyed off the SAME
/// [`crate::bindings::surviving_ref_names`] survivor set — so this set is
/// exactly the emitted `pub fn` set, never wider (a phantom reference would fail
/// to link) and never narrower (an omitted wrapper would let its build-time
/// reach go un-exercised).
///
/// Returned sorted and deduplicated for a deterministic probe.
#[must_use]
pub fn surviving_wrapper_paths(pkg: &PkgInfo, slug: &str) -> Vec<String> {
    let kernel = crate::naming::rust_kernel_name(pkg.pkg_path());
    let mut paths: Vec<String> = crate::bindings::surviving_ref_names(pkg)
        .iter()
        .map(|ref_name| {
            let ident = crate::naming::wrapper_fn_ident(&kernel, ref_name);
            format!("crate::ffi::{slug}::{ident}")
        })
        .collect();
    paths.sort();
    paths.dedup();
    paths
}

/// Emit the probe `main.rs` that references every wrapper in `wrapper_paths` so
/// the linker retains the whole foreign surface.
///
/// The references live in a `#[used] static` array of function addresses. `#[used]`
/// is a CONTRACTUAL retention: it forbids the compiler and linker from dropping
/// the static (and, transitively, the wrapper bodies whose addresses it holds),
/// where a mere local binding fed to [`std::hint::black_box`] retains only by
/// optimiser happenstance. So each wrapper's transitive foreign call — and its
/// bound crate's link-time reach — is genuinely built and linked. The probe
/// still NEVER invokes a wrapper: taking an address runs no author logic, so the
/// only observable capability demand is whatever *building and linking* the
/// referenced surface demands. `black_box` in `main` additionally forbids
/// whole-program stripping of the static.
///
/// `wrapper_paths` MUST be non-empty; an empty surface is un-exercisable and the
/// caller rejects it (fail-closed) rather than emit a vacuous probe that would
/// link clean without exercising anything.
///
/// # Panics
///
/// Never in production use; `debug_assert!` documents the non-empty precondition
/// the caller upholds.
#[must_use]
pub fn emit_probe_main(wrapper_paths: &[String]) -> String {
    use std::fmt::Write as _;
    debug_assert!(
        !wrapper_paths.is_empty(),
        "emit_probe_main requires a non-empty surface; the caller rejects an empty survivor set"
    );
    let count = wrapper_paths.len();
    let mut out = String::new();
    out.push_str(
        "// Code generated by the Tier-2 link-reachability probe emitter. DO NOT EDIT.\n\
         //\n\
         // References — never invokes — every surviving FFI wrapper so the linker\n\
         // retains the package's whole foreign surface under the declared-scoped jail.\n\
         #![allow(unused_imports)]\n\n",
    );
    // The addresses are stored as `usize` (not `*const ()`): a `static` must be
    // `Sync`, which a raw pointer is not, but the numeric address value still
    // names each wrapper symbol, so `#[used]` on the static contractually
    // retains the wrapper bodies whose addresses it holds.
    // Writing into a String is infallible.
    let _ = writeln!(out, "#[used]\nstatic TIER2_KEEP: [usize; {count}] = [");
    for path in wrapper_paths {
        out.push_str("        ");
        out.push_str(path);
        out.push_str(" as *const () as usize,\n");
    }
    out.push_str("];\n\nfn main() {\n    std::hint::black_box(&TIER2_KEEP);\n}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    // The fixture builders move a `serde_json::Value` into the `json!` macro; the
    // by-value take is the natural shape for a test factory.
    #[allow(clippy::needless_pass_by_value)]
    fn pkg_with(name: &str, fns: serde_json::Value) -> PkgInfo {
        PkgInfo::decode_json(
            &json!({
                "pkg": name,
                "name": name,
                "version": "1.0.0",
                "functions": fns,
                "errors": []
            })
            .to_string(),
        )
        .expect("decodes")
    }

    #[test]
    fn probe_references_every_surviving_wrapper_by_address_never_invokes() {
        // A plain fallible fn survives DCE and emits a `pub fn`; the probe must
        // reference it by address-of, not call it.
        let pkg = pkg_with(
            "semver",
            json!([{
                "name": "parse",
                "params": [{"name": "text", "type": "String", "ipeType": "String", "rustType": "&str"}],
                "results": [{"name": "", "type": "Result Error Version", "rustType": "Result<Version, Error>"}],
                "effect": "fallible"
            }]),
        );
        let paths = surviving_wrapper_paths(&pkg, "semver");
        assert!(!paths.is_empty(), "the fn survives DCE");
        assert!(
            paths.iter().all(|p| p.starts_with("crate::ffi::semver::")),
            "every path is app-crate-absolute under the slug's module: {paths:?}"
        );
        let src = emit_probe_main(&paths);
        // Address-of into a #[used] static — never an invocation (no `(` after a
        // path that would be a call).
        for p in &paths {
            assert!(
                src.contains(&format!("{p} as *const () as usize")),
                "the probe references `{p}` by address:\n{src}"
            );
            assert!(
                !src.contains(&format!("{p}(")),
                "the probe must NOT invoke `{p}`:\n{src}"
            );
        }
        assert!(
            src.contains("#[used]") && src.contains("static TIER2_KEEP"),
            "the probe contractually retains the surface via a #[used] static:\n{src}"
        );
        assert!(src.contains("std::hint::black_box(&TIER2_KEEP)"), "{src}");
        assert!(src.contains("fn main()"), "{src}");
    }

    #[test]
    fn wrapper_paths_are_the_surviving_ref_names_mapped_through_the_emitter_ident() {
        // Single source of truth: the path set is exactly the survivor set mapped
        // through the SAME wrapper_fn_ident the emitter uses — it cannot drift.
        let pkg = pkg_with(
            "semver",
            json!([{
                "name": "parse",
                "params": [{"name": "text", "type": "String", "ipeType": "String", "rustType": "&str"}],
                "results": [{"name": "", "type": "Result Error Version", "rustType": "Result<Version, Error>"}],
                "effect": "fallible"
            }]),
        );
        let kernel = crate::naming::rust_kernel_name(pkg.pkg_path());
        let expected: Vec<String> = crate::bindings::surviving_ref_names(&pkg)
            .iter()
            .map(|r| {
                format!(
                    "crate::ffi::semver::{}",
                    crate::naming::wrapper_fn_ident(&kernel, r)
                )
            })
            .collect();
        let mut expected_sorted = expected;
        expected_sorted.sort();
        assert_eq!(surviving_wrapper_paths(&pkg, "semver"), expected_sorted);
    }

    #[test]
    fn an_empty_surface_yields_no_paths() {
        // A package whose every fn drops out of DCE has no probeable surface; the
        // path set is empty and the caller rejects (never emits a vacuous probe).
        let pkg = pkg_with("empty", json!([]));
        assert!(surviving_wrapper_paths(&pkg, "empty").is_empty());
    }

    #[test]
    fn the_probe_output_is_deterministic_and_sorted() {
        // Two fns emitted in either inspection order produce the SAME sorted probe
        // — a certify/reject verdict must be reproducible (design §5).
        let a = pkg_with(
            "multi",
            json!([
                {"name": "beta", "params": [], "results": [{"name": "", "type": "u64", "rustType": "u64"}], "effect": "pure"},
                {"name": "alpha", "params": [], "results": [{"name": "", "type": "u64", "rustType": "u64"}], "effect": "pure"}
            ]),
        );
        let b = pkg_with(
            "multi",
            json!([
                {"name": "alpha", "params": [], "results": [{"name": "", "type": "u64", "rustType": "u64"}], "effect": "pure"},
                {"name": "beta", "params": [], "results": [{"name": "", "type": "u64", "rustType": "u64"}], "effect": "pure"}
            ]),
        );
        assert_eq!(
            surviving_wrapper_paths(&a, "multi"),
            surviving_wrapper_paths(&b, "multi")
        );
    }
}
