[package]
name = "ipe_canon"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
ipe_intern = { path = "../intern" }
ipe_diagnostics = { path = "../diagnostics" }
ipe_syntax = { path = "../syntax" }
ipe_kernels = { path = "../kernels" }

[dev-dependencies]
ipe_parse = { path = "../parse" }

[lints]
workspace = true
