//! Semantic-parity gate: the hand-ported parser must produce the same
//! `Block`/`Span` tree as `Ipe.Markdown` over the shared corpus.
//!
//! The expected trees are NOT hand-authored: they are snapshotted from an `ipe`
//! run of `examples/shapes/script/markdown-parity` (the `Ipe.Markdown`
//! serializer), regenerated by the `gen-markdown-parity` binary and committed as
//! `snapshot.txt`. This standing test re-parses each corpus source with the
//! port and asserts its canonical S-expression equals the snapshot's — so
//! `Ipe.Markdown` stays the single source of truth and any drift (in the port
//! OR in `Ipe.Markdown` without regeneration) reddens the build.

/// The committed snapshot produced by an `ipe` run of the parity serializer.
pub const SNAPSHOT: &str = include_str!("parity/snapshot.txt");

/// One corpus entry parsed out of the snapshot: name, raw Markdown source, and
/// the expected canonical block S-expression.
#[derive(Debug)]
pub struct Entry {
    pub name: String,
    pub source: String,
    pub blocks: String,
}

/// Parse the framed snapshot into its entries. Each frame is:
/// ```text
/// === <name> ===
/// --- source ---
/// <source, possibly multi-line>
/// --- blocks ---
/// <block sexpr, possibly multi-line>
/// --- end ---
/// ```
#[must_use]
pub fn parse_snapshot(text: &str) -> Vec<Entry> {
    let mut entries = Vec::new();
    let lines: Vec<&str> = text.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let Some(line) = lines.get(i) else { break };
        let Some(name) = line
            .strip_prefix("=== ")
            .and_then(|s| s.strip_suffix(" ==="))
        else {
            i += 1;
            continue;
        };
        // Expect the fixed section markers; collect until the next marker.
        i += 1;
        if lines.get(i).copied() != Some("--- source ---") {
            continue;
        }
        i += 1;
        let source = collect_until(&lines, &mut i, "--- blocks ---");
        let blocks = collect_until(&lines, &mut i, "--- end ---");
        entries.push(Entry {
            name: name.to_owned(),
            source,
            blocks,
        });
    }
    entries
}

/// Collect lines from `*i` up to (not including) the `marker` line, advancing
/// `*i` past the marker. Joins with `\n`.
fn collect_until(lines: &[&str], i: &mut usize, marker: &str) -> String {
    let mut collected: Vec<&str> = Vec::new();
    while let Some(&line) = lines.get(*i) {
        if line == marker {
            *i += 1;
            break;
        }
        collected.push(line);
        *i += 1;
    }
    collected.join("\n")
}

#[cfg(test)]
mod tests {
    use super::super::parse::parse_blocks;
    use super::super::sexpr::blocks_to_sexpr;
    use super::{SNAPSHOT, parse_snapshot};

    #[test]
    fn snapshot_is_non_empty() {
        let entries = parse_snapshot(SNAPSHOT);
        assert!(
            entries.len() >= 20,
            "parity corpus shrank unexpectedly: {} entries",
            entries.len()
        );
    }

    /// The port's tree equals `Ipe.Markdown`'s tree for every corpus document.
    /// A divergence here means the hand-port drifted from the SSOT parser (or
    /// the snapshot was regenerated after an `Ipe.Markdown` change and the port
    /// was not updated to match) — either way the parse SSOT is broken.
    #[test]
    fn port_matches_ipe_markdown_snapshot() {
        for entry in parse_snapshot(SNAPSHOT) {
            let got = blocks_to_sexpr(&parse_blocks(&entry.source));
            assert_eq!(
                got, entry.blocks,
                "parity drift on `{}`\n  source: {:?}\n  expected (Ipe.Markdown):\n{}\n  got (port):\n{}",
                entry.name, entry.source, entry.blocks, got
            );
        }
    }
}
